### PR TITLE
Exporting lists of user stories

### PR DESCRIPTION
**Pull request by avdgaag**

### CODE REVIEW

**Comment by avdgaag** [comment]
@ariejan Why export to Excel? Would you expect user stories expressed in columns? Or just a list of titles? Then CSV would suffice, no?

**Comment by ariejan** [comment]
@avdgaag Just two columns I think: Story, Estimate.

The thing is that managers (like The Grote Hoekjan) want to easily copy paste user stories in other documents. Being able to open those stories in a tool they know and trust, like Excel or Numbers, would be a good thing.

**Comment by avdgaag** [comment]
Right… but this app will know nothing about estimates. Tools like Pivotal Tracker are better suited for that, no?

**Comment by ariejan** [comment]
Ah. Right.

**Comment by avdgaag** [comment]
So… how many of the others have you implemented yet? :)

**Comment by ariejan** [comment]
Dude, I have my own side-project where I'm waiting for _your_ contributions.

**Pull request merged**
